version: '3.1'

services:
  db:
    image: postgres:12.2
    restart: always
    environment:
       POSTGRES_PASSWORD: test
       POSTGRES_USER: test
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql